export const AppPermissions = {
  HOME_READ: 'HOME_READ',
  REQUISITION_READ: 'REQUISITION_READ',
  REQUISITION_CREATE: 'REQUISITION_CREATE',
  REQUISITION_EDIT: 'REQUISITION_EDIT',
  CANDIDATE_READ: 'CANDIDATE_READ',
  CANDIDATE_CREATE: 'CANDIDATE_CREATE',
  CANDIDATE_EDIT: 'CANDIDATE_EDIT',
  SELECTION_READ: 'SELECTION_READ',
  SELECTION_CREATE: 'SELECTION_CREATE',
  SELECTION_EDIT: 'SELECTION_EDIT',
  QUESTIONNAIRE_READ: 'QUESTIONNAIRE_READ',
  QUESTIONNAIRE_CREATE: 'QUESTIONNAIRE_CREATE',
  QUESTIONNAIRE_EDIT: 'QUESTIONNAIRE_EDIT',
  TRACKING_READ: 'TRACKING_READ',
  REPORT_READ: 'REPORT_READ',
  SETTINGS_USERS_READ: 'SETTINGS_USERS_READ',
  SETTINGS_GROUPS_READ: 'SETTINGS_GROUPS_READ',
  SETTINGS_CATALOGS_READ: 'SETTINGS_CATALOGS_READ',
  SETTINGS_NOTIFICATIONS_READ: 'SETTINGS_NOTIFICATIONS_READ',
  SETTINGS_SYSTEM_READ: 'SETTINGS_SYSTEM_READ',
} as const;

export type AppPermission = (typeof AppPermissions)[keyof typeof AppPermissions];
