export {
  resolveRequisitionFieldLabel as resolveWizardFieldLabel,
  resolveRequisitionStepLabel as resolveWizardStepLabel,
  resolveRequisitionStepStepperLabel as resolveWizardStepperStepLabel,
  REQUISITION_WIZARD_NEW_TITLE,
  REQUISITION_WIZARD_EDIT_TITLE,
  REQUISITION_WIZARD_CONTINUE,
  REQUISITION_WIZARD_PREVIOUS,
  REQUISITION_WIZARD_CANCEL,
  REQUISITION_WIZARD_SAVE,
  REQUISITION_WIZARD_CREATE,
  REQUISITION_WIZARD_SAVING,
  REQUISITION_WIZARD_CREATING,
  REQUISITION_WIZARD_LOADING,
  REQUISITION_WIZARD_PROGRESS_ARIA,
  REQUISITION_SCOPE_HINT,
  REQUISITION_SCOPE_COUNTRY,
  REQUISITION_SCOPE_COVERAGE,
  REQUISITION_SCOPE_LOADING,
  requisitionWizardCreateSubtitle,
  requisitionWizardEditSubtitle,
  requisitionWizardStepOf,
  requisitionWizardStepAria,
} from '../../../core/i18n/requisition-wizard-labels';
