CANCELLATION_REASON_EN_BY_ID: dict[str, str] = {
    "catalogs.entry.cancellationType": "Cancellation type",
    "catalogs.entry.cancellationReason": "Cancellation reasons",
    "catalogs.column.cancellationType": "Cancellation type",
    "catalogs.field.cancellationType": "Cancellation type",
    "catalogs.field.allCancellationTypes": "All types",
    "catalogs.field.name": "Name",
    "catalogs.cancellationReason.newButton": "New cancellation reason",
    "catalogs.cancellationReason.newTitle": "New cancellation reason",
    "catalogs.cancellationReason.editTitle": "Edit cancellation reason",
    "catalogs.cancellationType.newButton": "New cancellation type",
    "catalogs.cancellationType.newTitle": "New cancellation type",
    "catalogs.cancellationType.editTitle": "Edit cancellation type",
    "common.search": "Search",
    "catalogs.cancellationType.value.CLIENT": "Client",
    "catalogs.cancellationReason.value.PROFILE_CHANGE": "Profile change",
    "catalogs.cancellationReason.value.CONTRACT_CANCEL_NONPAYMENT": "Contract cancelled for non-payment",
    "catalogs.cancellationReason.value.PROJECT_CANCEL": "Project cancelled",
    "catalogs.cancellationReason.value.LACK_OF_FEEDBACK": "Lack of feedback",
    "catalogs.cancellationReason.value.PERM_FLEX": "PERM FLEX",
    "catalogs.cancellationReason.value.PROJECT_TO_SUCCESS": "Project to success",
    "catalogs.cancellationReason.value.CLIENT_REFERRAL": "Client referral",
    "catalogs.cancellationReason.value.PROJECT_POSTPONED": "Project postponed",
}

APPEND_SOURCES: dict[str, str] = {
    "common.search": "Buscar",
    "catalogs.cancellationType.value.CLIENT": "Cliente",
    "catalogs.cancellationReason.value.PROFILE_CHANGE": "Cambio de perfil",
    "catalogs.cancellationReason.value.CONTRACT_CANCEL_NONPAYMENT": "Cancelación de contrato por falta de pago",
    "catalogs.cancellationReason.value.PROJECT_CANCEL": "Cancelación de proyecto",
    "catalogs.cancellationReason.value.LACK_OF_FEEDBACK": "Falta de retroalimentación",
    "catalogs.cancellationReason.value.PERM_FLEX": "PERM FLEX",
    "catalogs.cancellationReason.value.PROJECT_TO_SUCCESS": "Proyecto al Exito",
    "catalogs.cancellationReason.value.CLIENT_REFERRAL": "Referido del cliente",
    "catalogs.cancellationReason.value.PROJECT_POSTPONED": "Se pospone el proyecto",
}
