CANDIDATES_EN_BY_ID: dict[str, str] = {
    "candidates.list.subtitle": "Candidate administration in the system",
    "candidates.list.new": "New candidate",
    "candidates.list.search": "Search candidate",
    "candidates.list.searchPlaceholder": "Name, email…",
    "candidates.list.loadError": "Could not load candidates",
    "candidates.list.col.id": "ID",
    "candidates.list.col.firstName": "First name",
    "candidates.list.col.lastName": "Last name",
    "candidates.list.col.email": "Email",
    "candidates.list.col.phone": "Phone",
    "candidates.list.col.city": "City",
    "candidates.list.col.source": "Source",
    "candidates.list.col.active": "Active",
    "candidates.list.col.createdAt": "Created",
    "candidates.source.portal": "Portal",
    "candidates.source.recruiterExcelBulk": "Recruiter Excel bulk",
    "candidates.form.titleEdit": "Edit candidate",
    "candidates.form.subtitle": "Complete the candidate information",
    "candidates.form.loading": "Loading...",
    "candidates.form.gender.female": "Female",
    "candidates.form.gender.male": "Male",
    "candidates.form.source.manual": "Manual entry",
    "candidates.form.source.jobboard": "Job board",
    "candidates.form.source.buc": "BUC",
    "candidates.form.created": "Candidate created",
    "candidates.form.updated": "Candidate updated",
    "candidates.form.saveError": "Could not save the candidate",
    "candidates.form.loadError": "Could not load the candidate",
    "candidates.form.countriesError": "Could not load countries",
    "candidates.form.statesError": "Could not load states",
    "candidates.form.municipalitiesError": "Could not load municipalities",
    "candidates.form.neighborhoodsError": "Could not load neighborhoods",
    "candidates.form.noNeighborhoods": "No neighborhoods for that postal code",
    "paginator.itemsPerPage": "Items per page:",
    "paginator.nextPage": "Next page",
    "paginator.previousPage": "Previous page",
    "paginator.firstPage": "First page",
    "paginator.lastPage": "Last page",
    "paginator.rangeEmpty": "0 of {total}",
    "paginator.range": "{start} – {end} of {total}",
    "candidateProfile.field.source": "Source",
}
