CANDIDATE_ACCOUNTS_EN_BY_ID: dict[str, str] = {
    "nav.main.candidateAccounts": "Candidate accounts",
    "candidateAccounts.pageTitle": "Candidate accounts",
    "candidateAccounts.pageSubtitle": "Candidate portal account administration",
    "candidateAccounts.new": "New account",
    "candidateAccounts.empty": "No candidate accounts",
    "candidateAccounts.filter.email": "Search email",
    "candidateAccounts.col.email": "Email",
    "candidateAccounts.col.candidate": "Candidate",
    "candidateAccounts.col.status": "Registration status",
    "candidateAccounts.col.active": "Active",
    "candidateAccounts.col.lastLogin": "Last login",
    "candidateAccounts.dialog.create": "Create account",
    "candidateAccounts.dialog.edit": "Edit account",
    "candidateAccounts.field.email": "Candidate email",
    "candidateAccounts.field.sendMail": "Send registration email",
    "candidateAccounts.field.mustChange": "Must change password",
    "candidateAccounts.field.registerStatus": "Registration status",
    "candidateAccounts.status.pending": "Email pending",
    "candidateAccounts.status.email": "Email verified",
    "candidateAccounts.status.phone": "Phone verified",
    "candidateAccounts.hard.title": "Delete permanently",
    "candidateAccounts.hard.hint": "Type the account email to confirm irreversible deletion.",
    "candidateAccounts.hard.confirm": "Delete permanently",
    "candidateAccounts.hard.button": "Permanent delete",
    "candidateAccounts.save": "Save",
    "candidateAccounts.saving": "Saving…",
    "candidateAccounts.errors.list": "Could not load the list",
    "candidateAccounts.errors.save": "Could not save the account",
    "candidateAccounts.errors.active": "Could not update the active status",
    "candidateAccounts.errors.delete": "Could not delete the account",
    "candidateAccounts.errors.hard": "Could not permanently delete the account",
    "candidateAccounts.success.saved": "Account saved",
    "candidateAccounts.success.deleted": "Account deleted (soft)",
    "candidateAccounts.success.hard": "Account permanently deleted",
    "candidateAccounts.confirm.soft": "Soft-delete account {email}?",
}
