DOCUMENT_TEMPLATES_EN_BY_ID: dict[str, str] = {
    "nav.settings.documentTemplates": "Document templates",
    "applicationsDialog.actions.generateDocuments": "Generate documents",
    "documentTemplates.pageTitle": "Document templates",
    "documentTemplates.tab.variables": "Variables",
    "documentTemplates.tab.templates": "Templates",
    "documentTemplates.variables.newButton": "New variable",
    "documentTemplates.variables.search": "Search variable",
    "documentTemplates.variables.col.code": "Code",
    "documentTemplates.variables.col.label": "Label",
    "documentTemplates.variables.col.description": "Description",
    "documentTemplates.variables.col.inUse": "In use",
    "documentTemplates.variables.col.active": "Active",
    "documentTemplates.variables.empty": "No variables configured",
    "documentTemplates.variables.dialog.new": "New variable",
    "documentTemplates.variables.dialog.edit": "Edit variable",
    "documentTemplates.variables.field.origin": "Origin",
    "documentTemplates.variables.field.source": "Field",
    "documentTemplates.variables.field.code": "Code",
    "documentTemplates.variables.field.label": "Label",
    "documentTemplates.variables.field.description": "Description",
    "documentTemplates.variables.field.active": "Active",
    "documentTemplates.variables.codeHint": "The code is generated from the selected field and cannot be changed.",
    "documentTemplates.variables.noFields": "No fields available for this origin",
    "documentTemplates.variables.origin.candidate": "Candidate",
    "documentTemplates.variables.origin.position": "Position",
    "documentTemplates.variables.origin.recruiter": "Recruiter",
    "documentTemplates.variables.origin.application": "Application",
    "documentTemplates.variables.origin.company": "Company",
    "documentTemplates.variables.inUse.yes": "Yes",
    "documentTemplates.variables.inUse.no": "No",
    "documentTemplates.variables.errors.list": "Could not load variables",
    "documentTemplates.variables.errors.save": "Could not save the variable",
    "documentTemplates.variables.errors.fields": "Could not load available fields",
    "documentTemplates.variables.errors.delete": "Could not delete the variable",
    "documentTemplates.variables.success.saved": "Variable saved",
    "documentTemplates.variables.success.deleted": "Variable deleted",
    "documentTemplates.variables.deleteConfirm": 'Delete variable "{code}"? This action cannot be undone.',
    "documentTemplates.templates.newButton": "New template",
    "documentTemplates.templates.search": "Search template",
    "documentTemplates.templates.col.name": "Name",
    "documentTemplates.templates.col.fileName": "File",
    "documentTemplates.templates.col.active": "Active",
    "documentTemplates.templates.col.variables": "Variables used",
    "documentTemplates.templates.empty": "No document templates configured",
    "documentTemplates.templates.dialog.new": "New document template",
    "documentTemplates.templates.dialog.edit": "Edit document template",
    "documentTemplates.templates.field.name": "Name",
    "documentTemplates.templates.field.file": ".docx file",
    "documentTemplates.templates.pickFile": "Select .docx file",
    "documentTemplates.templates.field.active": "Active",
    "documentTemplates.templates.fileHint": "Only .docx files. Variables are validated when selected.",
    "documentTemplates.templates.fileCurrent": "Current file",
    "documentTemplates.templates.validVars": "Valid variables",
    "documentTemplates.templates.invalidVars": "Unrecognized variables",
    "documentTemplates.templates.validating": "Validating file...",
    "documentTemplates.templates.preview.title": "Document preview",
    "documentTemplates.templates.preview.empty": "Select a .docx file to preview",
    "documentTemplates.templates.preview.loading": "Generating preview...",
    "documentTemplates.templates.preview.error": "Could not show the preview",
    "documentTemplates.templates.preview.zoomToolbar": "Preview zoom",
    "documentTemplates.templates.preview.zoomIn": "Zoom in preview",
    "documentTemplates.templates.preview.zoomOut": "Zoom out preview",
    "documentTemplates.templates.preview.zoomReset": "Reset zoom",
    "documentTemplates.templates.download": "Download",
    "documentTemplates.templates.errors.list": "Could not load templates",
    "documentTemplates.templates.errors.save": "Could not save the template",
    "documentTemplates.templates.errors.load": "Could not load the template",
    "documentTemplates.templates.errors.validate": "Could not validate the file",
    "documentTemplates.templates.errors.download": "Could not get the download link",
    "documentTemplates.templates.errors.delete": "Could not delete the template",
    "documentTemplates.templates.errors.fileType": "Only .docx files are allowed",
    "documentTemplates.templates.success.saved": "Template saved",
    "documentTemplates.templates.success.deleted": "Template deleted",
    "documentTemplates.templates.deleteConfirm": 'Delete template "{name}"? This action cannot be undone.',
    "documentTemplates.cancel": "Cancel",
    "documentTemplates.save": "Save",
    "documentTemplates.saving": "Saving...",
    "documentTemplates.generate.title": "Generate documents",
    "documentTemplates.generate.col.name": "Template name",
    "documentTemplates.generate.col.actions": "Actions",
    "documentTemplates.generate.wordAction": "Generate Word document",
    "documentTemplates.generate.select": "Template",
    "documentTemplates.generate.confirm": "Generate and download",
    "documentTemplates.generate.generating": "Generating...",
    "documentTemplates.generate.empty": "No active templates available",
    "documentTemplates.generate.success": "Document generated",
    "documentTemplates.generate.errors.list": "Could not load templates",
    "documentTemplates.generate.errors.generate": "Could not generate the document",
    "common.clearFilters": "Clear",
}

APPEND_SOURCES: dict[str, str] = {
    "documentTemplates.variables.search": "Buscar variable",
    "documentTemplates.templates.search": "Buscar plantilla",
    "documentTemplates.templates.preview.zoomToolbar": "Zoom de vista previa",
    "documentTemplates.templates.preview.zoomIn": "Acercar vista previa",
    "documentTemplates.templates.preview.zoomOut": "Alejar vista previa",
    "documentTemplates.templates.preview.zoomReset": "Restablecer zoom",
    "common.clearFilters": "Limpiar",
}
