"""English targets for positions.* XLF ids."""

POSITIONS_EN_BY_ID: dict[str, str] = {
    "positions.duplicate.nameSuffix": " (Duplicated)",
    "positions.duplicate.fallbackName": "Position",
    "positions.pageTitle": "Positions",
    "positions.pageSubtitle": "Open requisition and position management",
    "positions.newButton": "New position",
    "positions.searchLabel": "Search position",
    "positions.searchPlaceholder": "Client, position, WO, code…",
    "positions.errors.load": "Could not load positions",
    "positions.column.clientKey": "Code",
    "positions.column.status": "Status",
    "positions.column.createdAt": "Created",
    "positions.column.name": "Name",
    "positions.column.ot": "OT",
    "positions.column.positions": "Positions",
    "positions.column.applicants": "Applicants",
    "positions.column.preselection": "Preselection",
    "positions.column.firstDay": "First day",
    "positions.column.group": "Group",
    "positions.column.supervisor": "Supervisor",
    "positions.column.cancellationScope": "Cancellation scope",
    "positions.reasonDialog.title": "Reason",
    "positions.reasonDialog.label": "Action reason",
    "positions.reasonDialog.required": "Reason is required",
    "positions.reasonDialog.confirm": "Confirm",
    "positions.reasonDialog.cancel": "Cancel",
    "positions.history.title": "Requisition history",
    "positions.history.empty": "No events recorded",
    "positions.history.close": "Close",
    "positions.reassign.title": "Reassign recruiter",
    "positions.reassign.user": "New recruiter",
    "positions.reassign.reason": "Reason (optional)",
    "positions.reassign.confirm": "Reassign",
    "positions.action.assign": "Assign recruiter",
    "positions.assign.title": "Assign recruiter",
    "positions.assign.user": "Recruiter",
    "positions.assign.confirm": "Assign",
    "positions.success.assign": "Recruiter assigned",
    "positions.action.goSelectionAria": "Go to selection",
    "positions.action.moreAria": "More actions",
    "positions.action.generatePublication": "Generate publication",
    "positions.action.publishOnPortal": "Publish on candidate portal",
    "dashboard.filter.dateFrom": "Creation date",
    "positions.filters.more": "Show more filters",
    "positions.filters.less": "Hide filters",
    "positions.filters.client": "Client",
    "positions.filters.requisitionType": "Requisition type",
    "positions.filters.coverageType": "Coverage type",
    "positions.filters.brand": "Company",
    "positions.filters.workplace": "Workplace",
    "positions.filters.shift": "Work schedule",
    "positions.filters.contractType": "Contract type",
    "positions.filters.education": "Education level",
    "positions.filters.responsibility": "Responsibility level",
    "positions.filters.clientPosition": "Client position",
    "positions.filters.createdBy": "Created by",
    "positions.filters.coordinator": "Coordinator",
    "positions.filters.recruiterAts": "ATS recruiter",
    "positions.filters.coordinatorAppian": "Appian coordinator",
    "positions.filters.recruiterAppian": "Appian recruiter",
    "positions.filters.closerAppian": "Appian closer",
    "positions.filters.requestType": "Request type",
    "positions.filters.appianUnavailable": "Unavailable",
    "positions.filters.deferredUnavailable": "Unavailable",
    "positions.filters.state": "State",
    "positions.filters.generalCategory": "Coverage category (C)",
    "positions.filters.questionnaire": "Form",
    "positions.success.publishOnPortal": "Vacancy published on the candidate portal",
    "positions.errors.publishOnPortal": "Could not publish the vacancy on the portal",
    "positions.confirm.publishOnPortal": "Publish this vacancy on the candidate portal?",
    "positions.errors.generatePublicationLoad": "Could not load the position contact information",
    "positions.publication.noTemplate.title": "Publication template required",
    "positions.publication.noTemplate.message": (
        "There is no publication template for the selected language. "
        "Create a template in Settings to generate the announcement."
    ),
    "positions.publication.noTemplate.ok": "OK",
    "positions.publication.noTemplate.create": "Create publication",
    "positions.publication.noTemplate.checkError": "Could not verify whether publication templates exist",
    "positions.cancelDialog.requisition": "Requisition",
    "positions.cancelDialog.show": "Show",
    "positions.cancelDialog.hide": "Hide",
    "positions.cancelDialog.candidates": "Candidates",
    "positions.cancelDialog.col.name": "Full name",
    "positions.cancelDialog.col.email": "Email",
    "positions.cancelDialog.col.phone": "Phone",
    "positions.cancelDialog.col.status": "Status",
    "positions.cancelDialog.type": "Cancellation type",
    "positions.cancelDialog.reason": "Reasons",
    "positions.cancelDialog.description": "Description (optional)",
    "positions.cancelDialog.evidence": "Evidence (optional)",
    "positions.cancelDialog.evidenceHint": "PDF, JPG, PNG, DOC, DOCX, XLS or XLSX. Maximum 10 MB.",
    "positions.cancelDialog.evidencePick": "Select file",
    "positions.cancelDialog.evidenceClear": "Remove",
    "positions.cancelDialog.evidenceInvalid": (
        "Invalid file. Use PDF, JPG, PNG, DOC, DOCX, XLS or XLSX up to 10 MB."
    ),
    "positions.cancelDialog.required": "Required field",
    "positions.cancelDialog.loadError": "Could not load cancellation impact",
    "positions.cancelDialog.reasonsError": "Could not load reasons",
    "positions.cancelDialog.criticalWarning": (
        "There are candidates in Preselection or First day. Do you want to continue with the cancellation?"
    ),
    "positions.cancelDialog.criticalTitle": "Confirm cancellation",
    "positions.cancelDialog.noCandidates": "No candidates associated with this position",
    "positions.errors.cancelEvidenceUpload": "Could not upload cancellation evidence",
    "positions.history.event.created": "Requisition created",
    "positions.history.event.statusChanged": "Status change",
    "positions.history.event.assigned": "Recruiter assignment",
    "positions.history.event.reassigned": "Recruiter reassignment",
    "positions.history.event.groupChanged": "Group change",
    "positions.history.event.cancellationRequested": "Cancellation request",
    "positions.history.event.cancellationAuthorized": "Cancellation authorized",
    "positions.history.event.cancellationRejected": "Cancellation rejected",
    "positions.history.event.cancellationExecuted": "Cancellation executed",
    "positions.history.event.directCancellation": "Direct cancellation",
}
