"""English targets for questionnaires.* XLF ids.

Placeholders like {name} / {text} / {eligible} match <x id="..."> in the source.
"""

QUESTIONNAIRE_EN_BY_ID: dict[str, str] = {
    # Nav / titles
    "questionnaires.pageTitle": "Questionnaires",
    "questionnaires.shell.hint": "Content for this section will be implemented in later module tasks.",
    "questionnaires.nav.questions": "Questions",
    "questionnaires.nav.questionTypes": "Question types",
    "questionnaires.nav.questionnaires": "Questionnaires",
    "questionnaires.nav.exams": "Exams",
    "questionnaires.nav.categories": "Categories",
    "questionnaires.nav.questionTags": "Question tags",
    "questionnaires.categories.title": "Knowledge categories",
    "questionnaires.tags.title": "Question tags",
    "questionnaires.questions.title": "Question bank",
    "questionnaires.questionTypes.title": "Question types",
    "questionnaires.questionnaires.title": "Questionnaires",
    "questionnaires.exams.title": "Exams",
    # Categories
    "questionnaires.categories.tab.categories": "Categories",
    "questionnaires.categories.tab.tags": "Tags",
    "questionnaires.categories.newButton": "New category",
    "questionnaires.categories.newTitle": "New category",
    "questionnaires.categories.editTitle": "Edit category",
    "questionnaires.categories.field.name": "Name",
    "questionnaires.categories.field.parent": "Parent category",
    "questionnaires.categories.field.noParent": "No parent category",
    "questionnaires.categories.field.description": "Description",
    "questionnaires.categories.col.parent": "Parent",
    "questionnaires.categories.empty": "No categories registered",
    "questionnaires.categories.errors.list": "Could not load categories",
    "questionnaires.categories.errors.save": "Could not save category",
    "questionnaires.categories.errors.delete": "Could not delete category",
    "questionnaires.categories.success.saved": "Category saved",
    "questionnaires.categories.success.deleted": "Category deleted",
    "questionnaires.categories.deleteConfirm": 'Delete category "{name}"? This action cannot be undone.',
    # Tags
    "questionnaires.tags.newButton": "New tag",
    "questionnaires.tags.newTitle": "New tag",
    "questionnaires.tags.editTitle": "Edit tag",
    "questionnaires.tags.field.name": "Name",
    "questionnaires.tags.field.description": "Description",
    "questionnaires.tags.empty": "No tags registered",
    "questionnaires.tags.errors.list": "Could not load tags",
    "questionnaires.tags.errors.save": "Could not save tag",
    "questionnaires.tags.errors.delete": "Could not delete tag",
    "questionnaires.tags.success.saved": "Tag saved",
    "questionnaires.tags.success.deleted": "Tag deleted",
    "questionnaires.tags.deleteConfirm": 'Delete tag "{name}"? This action cannot be undone.',
    # Shared columns
    "questionnaires.common.col.name": "Name",
    "questionnaires.common.col.description": "Description",
    "questionnaires.common.col.scope": "Scope",
    # Exams
    "questionnaires.exams.newButton": "New exam",
    "questionnaires.exams.empty": "No exams registered",
    "questionnaires.exams.filter.name": "Search by name",
    "questionnaires.exams.filter.questionnaire": "Questionnaire",
    "questionnaires.exams.filter.status": "Status",
    "questionnaires.exams.filter.all": "All",
    "questionnaires.exams.filter.apply": "Search",
    "questionnaires.exams.filter.clear": "Clear",
    "questionnaires.exams.col.name": "Name",
    "questionnaires.exams.col.questionnaire": "Questionnaire",
    "questionnaires.exams.col.status": "Status",
    "questionnaires.exams.col.questions": "No. of questions",
    "questionnaires.exams.col.attempts": "Max. attempts",
    "questionnaires.exams.attemptsUnlimited": "Unlimited",
    "questionnaires.exams.status.draft": "Draft",
    "questionnaires.exams.status.published": "Published",
    "questionnaires.exams.status.archived": "Archived",
    "questionnaires.exams.dialog.newTitle": "New exam",
    "questionnaires.exams.dialog.editTitle": "Edit exam",
    "questionnaires.exams.tab.general": "General information",
    "questionnaires.exams.tab.questionSelection": "Question selection",
    "questionnaires.exams.tab.description": "Description",
    "questionnaires.exams.field.questionnaire": "Published questionnaire",
    "questionnaires.exams.field.name": "Name",
    "questionnaires.exams.field.description": "Description",
    "questionnaires.exams.field.numberOfQuestions": "Number of questions",
    "questionnaires.exams.field.defaultWeight": "Default weight",
    "questionnaires.exams.field.timeLimitSeconds": "Time limit per question (sec)",
    "questionnaires.exams.field.totalTimeMinutes": "Total time (min)",
    "questionnaires.exams.field.acceptancePercent": "Pass threshold (%)",
    "questionnaires.exams.field.maxAttempts": "Maximum attempts",
    "questionnaires.exams.field.maxAttemptsHint": "Empty = unlimited. Minimum 1 if specified.",
    "questionnaires.exams.maxAttempts.hintTitle": "What are maximum attempts?",
    "questionnaires.exams.maxAttempts.hintBody": (
        "How many times each candidate can take the exam. If left empty, attempts are unlimited. "
        "If you enter a number, it must be at least 1."
    ),
    "questionnaires.exams.maxAttempts.exampleTitle": "Examples",
    "questionnaires.exams.maxAttempts.exampleEmpty": "Empty — unlimited attempts",
    "questionnaires.exams.maxAttempts.exampleOne": "1 — one opportunity per candidate",
    "questionnaires.exams.maxAttempts.exampleThree": "3 — up to three attempts",
    "questionnaires.exams.field.helpLink": "Help",
    "questionnaires.exams.field.retryDelayDays": "Days between retries",
    "questionnaires.exams.field.startDate": "Window start",
    "questionnaires.exams.field.endDate": "Window end",
    "questionnaires.exams.field.generationConfig": "Question selection rules",
    "questionnaires.exams.field.randomSeed": "Random seed",
    "questionnaires.exams.randomSeed.hintTitle": "What is the random seed?",
    "questionnaires.exams.randomSeed.hintBody": (
        "Optional. If left empty, each attempt may get a different subset of questions. "
        "If you enter a number (e.g. 42), the selection will be reproducible for testing or audit."
    ),
    "questionnaires.exams.randomSeed.exampleTitle": "Examples",
    "questionnaires.exams.randomSeed.exampleEmpty": "Empty — selection varies between attempts",
    "questionnaires.exams.randomSeed.exampleFixed": "42 — same question selection when repeating the exam",
    "questionnaires.exams.generation.intro": (
        "Define how questionnaire questions are chosen when an attempt starts. "
        "If no filters are applied, all linked questions will be used."
    ),
    "questionnaires.exams.generation.questionTypes": "Allowed question types",
    "questionnaires.exams.generation.questionTypesHint": "None selected = all types in the questionnaire.",
    "questionnaires.exams.generation.difficultyFilter": "Filter by difficulty",
    "questionnaires.exams.generation.difficultyMin": "Minimum difficulty (1-5)",
    "questionnaires.exams.generation.difficultyMax": "Maximum difficulty (1-5)",
    "questionnaires.exams.generation.categories": "Knowledge categories (optional)",
    "questionnaires.exams.generation.tags": "Tags (optional)",
    "questionnaires.exams.generation.tagsHint": (
        "None selected = no tag filter. With several, the question must have at least one."
    ),
    "questionnaires.exams.generation.excludeQuestions": "Exclude questions from the questionnaire",
    "questionnaires.exams.generation.jsonPreview": "Technical preview (JSON)",
    "questionnaires.exams.generation.advancedJson": "Advanced JSON editing",
    "questionnaires.exams.generation.useAdvancedJson": "Use manual JSON (advanced users only)",
    "questionnaires.exams.generation.unsupportedJson": (
        "This exam has JSON with fields that cannot be edited in the form. Review advanced editing."
    ),
    "questionnaires.exams.generation.excludeHint": "Select a questionnaire to exclude specific questions.",
    "questionnaires.exams.field.status": "Status",
    "questionnaires.exams.questionsAvailable": "Questions available in questionnaire:",
    "questionnaires.exams.eligibleQuestions": "Eligible questions after filters:",
    "questionnaires.exams.noPublishedQuestionnaires": "No published questionnaires available",
    "questionnaires.exams.errors.insufficientEligibleOne": (
        "There is only 1 eligible question after the filters; the exam requires {requested}. "
        "The questionnaire has {available}."
    ),
    "questionnaires.exams.errors.insufficientEligibleMany": (
        "There are only {eligible} eligible questions after the filters; the exam requires {requested}. "
        "The questionnaire has {available}."
    ),
    "questionnaires.exams.errors.list": "Could not load exams",
    "questionnaires.exams.errors.load": "Could not load exam",
    "questionnaires.exams.errors.save": "Could not save exam",
    "questionnaires.exams.errors.delete": "Could not delete exam",
    "questionnaires.exams.errors.maxAttempts": "Maximum attempts must be at least 1 or left empty",
    "questionnaires.exams.success.saved": "Exam saved",
    "questionnaires.exams.success.deleted": "Exam deleted",
    "questionnaires.exams.deleteConfirm": 'Delete exam "{name}"? This action cannot be undone.',
    # Questionnaires (bank)
    "questionnaires.questionnaires.newButton": "New questionnaire",
    "questionnaires.questionnaires.empty": "No questionnaires registered",
    "questionnaires.questionnaires.filter.name": "Search by name",
    "questionnaires.questionnaires.filter.category": "Category",
    "questionnaires.questionnaires.filter.status": "Status",
    "questionnaires.questionnaires.filter.all": "All",
    "questionnaires.questionnaires.filter.apply": "Search",
    "questionnaires.questionnaires.filter.clear": "Clear",
    "questionnaires.questionnaires.col.name": "Name",
    "questionnaires.questionnaires.col.category": "Category",
    "questionnaires.questionnaires.col.status": "Status",
    "questionnaires.questionnaires.col.questions": "Questions",
    "questionnaires.questionnaires.status.draft": "Draft",
    "questionnaires.questionnaires.status.published": "Published",
    "questionnaires.questionnaires.status.archived": "Archived",
    "questionnaires.questionnaires.publishButton": "Publish",
    "questionnaires.questionnaires.publishConfirm": "Publish this questionnaire? It cannot be edited afterwards.",
    "questionnaires.questionnaires.publishSuccess": "Questionnaire published",
    "questionnaires.questionnaires.publishError": "Could not publish questionnaire",
    "questionnaires.questionnaires.archiveButton": "Archive",
    "questionnaires.questionnaires.archiveConfirm": (
        "Archive this questionnaire? It will no longer be available for new exams, "
        "but existing exams will keep their reference."
    ),
    "questionnaires.questionnaires.archiveSuccess": "Questionnaire archived",
    "questionnaires.questionnaires.archiveError": "Could not archive questionnaire",
    "questionnaires.questionnaires.duplicateButton": "Duplicate",
    "questionnaires.questionnaires.duplicateConfirm": (
        "Create a draft copy of this questionnaire? You can edit and publish it when it is ready."
    ),
    "questionnaires.questionnaires.duplicateSuccess": "Questionnaire duplicated as draft",
    "questionnaires.questionnaires.duplicateError": "Could not duplicate questionnaire",
    "questionnaires.questionnaires.dialog.newTitle": "New questionnaire",
    "questionnaires.questionnaires.dialog.editTitle": "Edit questionnaire",
    "questionnaires.questionnaires.dialog.viewTitle": "View questionnaire",
    "questionnaires.questionnaires.field.name": "Name",
    "questionnaires.questionnaires.field.description": "Description",
    "questionnaires.questionnaires.field.category": "Category (optional)",
    "questionnaires.questionnaires.field.noCategory": "No category",
    "questionnaires.questionnaires.questions.title": "Assigned questions",
    "questionnaires.questionnaires.questions.add": "Add question",
    "questionnaires.questionnaires.questions.select": "Select question",
    "questionnaires.questionnaires.questions.empty": "No questions assigned",
    "questionnaires.questionnaires.questions.weight": "Weight",
    "questionnaires.questionnaires.questions.moveUp": "Move up",
    "questionnaires.questionnaires.questions.moveDown": "Move down",
    "questionnaires.questionnaires.categoryMismatch": (
        "Some questions belong to a different category than the questionnaire."
    ),
    "questionnaires.questionnaires.publishedLocked": "This questionnaire is published and cannot be edited.",
    "questionnaires.questionnaires.archivedLocked": "This questionnaire is archived and cannot be edited.",
    "questionnaires.questionnaires.errors.list": "Could not load questionnaires",
    "questionnaires.questionnaires.errors.load": "Could not load questionnaire",
    "questionnaires.questionnaires.errors.save": "Could not save questionnaire",
    "questionnaires.questionnaires.errors.delete": "Could not delete questionnaire",
    "questionnaires.questionnaires.success.saved": "Questionnaire saved",
    "questionnaires.questionnaires.success.deleted": "Questionnaire deleted",
    "questionnaires.questionnaires.deleteConfirm": 'Delete questionnaire "{name}"? This action cannot be undone.',
    # Questions
    "questionnaires.questions.newButton": "New question",
    "questionnaires.questions.empty": "No questions registered",
    "questionnaires.questions.filter.text": "Search",
    "questionnaires.questions.filter.category": "Category",
    "questionnaires.questions.filter.type": "Type",
    "questionnaires.questions.filter.all": "All",
    "questionnaires.questions.filter.apply": "Search",
    "questionnaires.questions.filter.clear": "Clear",
    "questionnaires.questions.col.text": "Statement",
    "questionnaires.questions.col.type": "Type",
    "questionnaires.questions.col.category": "Category",
    "questionnaires.questions.col.difficulty": "Difficulty",
    "questionnaires.questions.col.locked": "Locked",
    "questionnaires.questions.type.singleChoice": "Single choice",
    "questionnaires.questions.type.multipleChoice": "Multiple choice",
    "questionnaires.questions.type.yesNo": "Yes/No",
    "questionnaires.questions.type.open": "Open",
    "questionnaires.questionTypes.col.code": "Code",
    "questionnaires.questionTypes.col.label": "Label",
    "questionnaires.questionTypes.col.description": "Description",
    "questionnaires.questionTypes.desc.singleChoice": (
        "The candidate chooses a single correct option. Requires at least two options."
    ),
    "questionnaires.questionTypes.desc.multipleChoice": (
        "The candidate can select several correct options. Requires at least two options."
    ),
    "questionnaires.questionTypes.desc.yesNo": (
        "Binary question with two options and exactly one correct answer."
    ),
    "questionnaires.questionTypes.desc.open": "Free-text answer. Does not allow predefined options.",
    "questionnaires.questions.dialog.newTitle": "New question",
    "questionnaires.questions.dialog.editTitle": "Edit question",
    "questionnaires.questions.dialog.viewTitle": "View question",
    "questionnaires.questions.field.text": "Statement",
    "questionnaires.questions.field.type": "Type",
    "questionnaires.questions.field.category": "Category",
    "questionnaires.questions.field.difficulty": "Difficulty (1-5)",
    "questionnaires.questions.field.explanation": "Explanation",
    "questionnaires.questions.field.correctAnswer": "Correct answer",
    "questionnaires.questions.field.tags": "Tags",
    "questionnaires.questions.field.noTags": "No tags",
    "questionnaires.questions.options.title": "Options",
    "questionnaires.questions.options.text": "Option text",
    "questionnaires.questions.options.correct": "Correct",
    "questionnaires.questions.options.add": "Add option",
    "questionnaires.questions.lockedHint": "This question is locked and cannot be edited.",
    "questionnaires.questions.errors.list": "Could not load questions",
    "questionnaires.questions.errors.load": "Could not load question",
    "questionnaires.questions.errors.save": "Could not save question",
    "questionnaires.questions.errors.delete": "Could not delete question",
    "questionnaires.questions.errors.options": "Options are not valid for the selected type",
    "questionnaires.questions.success.saved": "Question saved",
    "questionnaires.questions.success.deleted": "Question deleted",
    "questionnaires.questions.deleteConfirm": 'Delete question "{text}"? This action cannot be undone.',
    # CSV panels
    "questionnaires.csv.knowledgeCategories": "Knowledge categories",
    "questionnaires.csv.tags": "Tags",
    "questionnaires.csv.questions": "Questions",
    "questionnaires.csv.questionOptions": "Question options",
    "questionnaires.csv.questionTags": "Question tags",
    "questionnaires.csv.questionnaires": "Questionnaires",
    "questionnaires.csv.questionnaireQuestions": "Questionnaire questions",
    "questionnaires.csv.exams": "Exams",
    "questionnaires.csv.publish": "Publish questionnaires",
}
