"""English targets for reports.* XLF ids."""

REPORTS_EN_BY_ID: dict[str, str] = {
    "reports.pageTitle": "Reports",
    "reports.nav.category.general": "General",
    "reports.nav.category.coverage": "Coverage",
    "reports.nav.category.vacancies": "Vacancies",
    "reports.nav.mmr": "MMR",
    "reports.nav.statusByRequisition": "Status by requisition",
    "reports.nav.processFunnel": "Process funnel",
    "reports.nav.consolidated": "Consolidated",
    "reports.nav.segmentedSummary": "Segmented summary",
    "reports.nav.topIncidents": "Top incidents",
    "reports.nav.metrics": "Metrics",
    "reports.nav.positionsInProcess": "Positions in process",
    "reports.nav.behavior": "Behavior",
    "reports.nav.requisitionsBySource": "Requisitions by source",
    "reports.action.update": "Update",
    "reports.action.clearFilters": "Clear filters",
    "reports.section.indicators": "Indicators",
    "reports.column.indicator": "Indicator",
    "reports.empty.matrix": "No data for the selected filters",
    "reports.kpi.fillRateCurrent": "Current fill rate",
    "reports.kpi.fillRatePrior": "Prior fill rate",
    "reports.kpi.fillRateYtd": "YTD fill rate",
    "reports.filter.country": "Country",
    "reports.filter.recruitmentType": "Recruitment type",
    "reports.filter.businessUnit": "Business units",
    "reports.filter.group": "Group",
    "reports.filter.year": "Year",
    "reports.filter.order": "Order",
    "reports.filter.recruiter": "Recruiter",
    "reports.filter.all": "All",
    "reports.filter.allFem": "All",
    "reports.filter.selectCountry": "Select country",
    "reports.recruitment.temp": "Temporary (TEMP)",
    "reports.recruitment.temporary": "Temporary (TEMPORARY)",
    "reports.recruitment.permanent": "Permanent",
    "reports.mmr.title": "MMR report",
    "reports.mmr.subtitle": "Monthly fill rate and indicators",
    "reports.mmr.loadError": "Could not load the MMR report. Please try again.",
    "reports.rbm.title": "Requisitions by month",
    "reports.rbm.subtitle": "Monthly volume and indicators",
    "reports.rbm.loadError": "Could not load the Requisitions by month report. Please try again.",
    "reports.perf.title": "Performance",
    "reports.perf.subtitle": "Performance summary by recruiter",
    "reports.perf.loadError": "Could not load the performance report. Please try again.",
    "reports.perf.kpiTitle": "FILL RATE",
    "reports.perf.filter.month": "Month",
    "reports.perf.col.recruiter": "Recruiter",
    "reports.perf.col.opening": "Opening orders",
    "reports.perf.col.temp": "Temporary orders obtained",
    "reports.perf.col.cancellations": "Cancelled orders",
    "reports.perf.col.associateStarts": "Associate starts (Placement)",
    "reports.perf.col.monthEnd": "Orders (month end)",
    "reports.perf.col.fillRate": "Fill rate",
    "reports.perf.col.cancelRate": "Cancellation rate",
    "reports.perf.col.total": "TOTAL",
    "reports.filter.businessUnitShort": "Business unit",
    "reports.filter.requisition": "Requisition",
    "reports.filter.status": "Status",
    "reports.filter.startDate": "Start date",
    "reports.filter.endDate": "End date",
    "reports.filter.client": "Client",
    "reports.filter.clientPlaceholder": "Search client",
    "reports.filter.clientClear": "Clear client",
    "reports.filter.orderNumber": "Order #{id}",
    "reports.sbr.subtitle": "Aggregated by requisition status",
    "reports.sbr.loadError": "Could not load the Status by requisition report. Please try again.",
    "reports.sbr.chartTitle": "Requisitions by status",
    "reports.sbr.empty": "No information",
    "reports.sbr.col.status": "Status",
    "reports.sbr.col.requisitions": "Requisitions",
    "reports.sbr.col.positions": "Number of positions",
    "reports.sbr.col.applicants": "Applicants",
    "reports.sbr.col.preselected": "Preselected",
    "reports.sbr.col.selected": "Selected",
    "reports.sbr.col.evaluated": "Evaluated",
    "reports.sbr.col.interviewed": "Interviewed",
    "reports.sbr.col.prehired": "Pre-hired",
    "reports.sbr.col.hired": "Hired",
    "reports.sbr.col.uncovered": "Uncovered",
    "reports.sbr.col.compliance": "Compliance %",
    "reports.sbr.col.digitalDocs": "Digital docs",
    "reports.sbr.status.covered": "Covered",
    "reports.sbr.status.partiallyCovered": "Partially covered",
    "reports.sbr.status.inAnalysis": "In analysis",
    "reports.sbr.status.inSelection": "In selection",
    "reports.sbr.status.cancelled": "Cancelled",
    "reports.sbr.status.cancellationRequested": "Cancellation requested",
    "reports.sbr.status.inProcess": "In process",
    "reports.pf.subtitle": "Candidate funnel by requisition",
    "reports.pf.loadError": "Could not load the Process funnel report. Please try again.",
    "reports.pf.chart.totalCoverage": "Total coverage",
    "reports.pf.chart.coverageByBrand": "Coverage by brand",
    "reports.pf.empty.brands": "No brands to display",
    "reports.pf.empty.noBrand": "No brand",
    "reports.month.jan": "Jan",
    "reports.month.feb": "Feb",
    "reports.month.mar": "Mar",
    "reports.month.apr": "Apr",
    "reports.month.may": "May",
    "reports.month.jun": "Jun",
    "reports.month.jul": "Jul",
    "reports.month.aug": "Aug",
    "reports.month.sep": "Sep",
    "reports.month.oct": "Oct",
    "reports.month.nov": "Nov",
    "reports.month.dec": "Dec",
    "reports.filter.dimension": "Dimension",
    "reports.filter.startDay": "Start day",
    "reports.filter.endDay": "End day",
    "reports.pager.range": "{from} - {to} of {total}",
    "reports.month.january": "January",
    "reports.month.february": "February",
    "reports.month.march": "March",
    "reports.month.april": "April",
    "reports.month.may": "May",
    "reports.month.june": "June",
    "reports.month.july": "July",
    "reports.month.august": "August",
    "reports.month.september": "September",
    "reports.month.october": "October",
    "reports.month.november": "November",
    "reports.month.december": "December",
    "reports.dim.none": "Summary (no dimension)",
    "reports.cons.status.created": "Created",
    "reports.cons.status.analysis": "Analysis",
    "reports.cons.status.selection": "Selection",
    "reports.cons.subtitle": "Summary of requisitions by status and day of the month",
    "reports.cons.loadError": "Could not load the Consolidated report. Please try again.",
    "reports.cons.kpi.totalRequisitions": "Total requisitions",
    "reports.cons.kpi.recruiters": "Recruiters",
    "reports.cons.kpi.reqPerRecruiter": "Req./Recruiters",
    "reports.cons.chart.status": "Requisitions by status",
    "reports.cons.section.detail": "Requisition details by status and days of the month",
    "reports.cons.col.statusDay": "Status/Day",
    "reports.cons.section.byDimension": "By dimension",
    "reports.cons.col.entity": "Entity",
    "reports.seg.subtitle": "Requisitions by status and totals by dimension",
    "reports.seg.loadError": "Could not load the Segmented summary. Please try again.",
    "reports.seg.section.daily": "Daily requisition summary by Group / Recruiter",
    "reports.seg.col.groupRecruiter": "Group/Recruiter",
    "reports.tops.subtitle": "Top incidents (metrics pending definition)",
    "reports.tops.dim.pendingAssignment": "Pending assignment",
    "reports.tops.title": "Top incidents - Requisitions {dim}",
    "reports.tops.col.coordinator": "Coordinator",
    "reports.tops.col.requis": "Reqs.",
    "reports.tops.col.businessUnit": "Business unit",
    "reports.tops.loadError": "Could not load the Top incidents report. Please try again.",
    "reports.met.subtitle": "Position, applicant, and hire metrics",
    "reports.met.titleBy": "Covered requisition metrics by {dim}",
    "reports.met.dim.byGroup": "By group",
    "reports.met.dim.byRecruiter": "By recruiter",
    "reports.met.dim.byClient": "By client",
    "reports.met.dim.byBusinessUnit": "By business unit",
    "reports.met.emptyChart": "No data to chart",
    "reports.met.col.positions": "Positions",
    "reports.met.col.avgHireDays": "Avg. hiring days",
    "reports.met.loadError": "Could not load the Metrics report. Please try again.",
    "reports.rip.subtitle": "On-time vs overdue and details by client",
    "reports.rip.chart.onTimeVsExpired": "In-process vs. overdue requisitions",
    "reports.rip.aria.pie": "On time vs overdue",
    "reports.rip.onTime": "On time",
    "reports.rip.expired": "Overdue",
    "reports.rip.chart.byYear": "In-process requisitions and number of applicants by year",
    "reports.rip.emptyYear": "No information by year",
    "reports.rip.aria.yearBars": "Bars by year",
    "reports.rip.clients": "Clients",
    "reports.rip.col.inProcess": "In process",
    "reports.rip.loadError": "Could not load the Requisitions in process report. Please try again.",
    "reports.beh.title": "Coverage behavior",
    "reports.beh.subtitle": "Fill rate, stages, and details by requisition",
    "reports.beh.chart.fillRate": "Fill rate",
    "reports.beh.chart.byType": "By requisition type",
    "reports.beh.chart.stages": "Candidate metrics by stage",
    "reports.beh.noData": "No data available",
    "reports.beh.section.covered": "Covered requisition behavior",
    "reports.beh.fill.positions": "Positions ({pct})",
    "reports.beh.fill.hired": "Hired ({pct})",
    "reports.beh.fill.uncovered": "Uncovered ({pct})",
    "reports.beh.col.createDate": "Creation date",
    "reports.beh.col.commitmentDate": "Commitment date",
    "reports.beh.col.coverageDate": "Coverage date",
    "reports.beh.col.daysCreateCoverage": "Time (days) Creation-Coverage",
    "reports.beh.col.daysCoverageCommitment": "Time (days) Coverage-Commitment",
    "reports.beh.col.positionsCount": "Number of positions",
    "reports.beh.col.qtyApplicants": "Number of applicants",
    "reports.beh.col.qtyPreselected": "Number preselected",
    "reports.beh.col.qtySelected": "Number selected",
    "reports.beh.col.qtyEvaluated": "Number evaluated",
    "reports.beh.col.qtyInterviewed": "Number interviewed",
    "reports.beh.col.qtyPrehired": "Number pre-hired",
    "reports.beh.col.qtyHired": "Number hired",
    "reports.beh.loadError": "Could not load the Behavior report. Please try again.",
    "reports.rbs.subtitle": "Performance by candidate source",
    "reports.rbs.col.source": "Recruitment source",
    "reports.rbs.col.hiredPct": "% Hired",
    "reports.rbs.col.notHired": "Not hired",
    "reports.rbs.col.notHiredPct": "% Not hired",
    "reports.rbs.col.sourceCoverage": "% Source coverage",
    "reports.rbs.loadError": "Could not load the Requisitions by recruitment source report. Please try again.",
}
