"""English targets for reports.* XLF ids."""

REPORTS_EN_BY_ID: dict[str, str] = {
    "reports.pageTitle": "Reports",
    "reports.nav.category.general": "General",
    "reports.nav.category.coverage": "Coverage",
    "reports.nav.category.vacancies": "Vacancies",
    "reports.nav.mmr": "MMR",
    "reports.nav.statusByRequisition": "Status by requisition",
    "reports.nav.processFunnel": "Process funnel",
    "reports.nav.consolidated": "Consolidated",
    "reports.nav.segmentedSummary": "Segmented summary",
    "reports.nav.topIncidents": "Top incidents",
    "reports.nav.metrics": "Metrics",
    "reports.nav.positionsInProcess": "Positions in process",
    "reports.nav.behavior": "Behavior",
    "reports.nav.requisitionsBySource": "Requisitions by source",
    "reports.action.update": "Update",
    "reports.action.clearFilters": "Clear filters",
    "reports.section.indicators": "Indicators",
    "reports.column.indicator": "Indicator",
    "reports.empty.matrix": "No data for the selected filters",
    "reports.kpi.fillRateCurrent": "Current fill rate",
    "reports.kpi.fillRatePrior": "Prior fill rate",
    "reports.kpi.fillRateYtd": "YTD fill rate",
    "reports.filter.country": "Country",
    "reports.filter.recruitmentType": "Recruitment type",
    "reports.filter.businessUnit": "Business units",
    "reports.filter.group": "Group",
    "reports.filter.year": "Year",
    "reports.filter.order": "Order",
    "reports.filter.recruiter": "Recruiter",
    "reports.filter.all": "All",
    "reports.filter.allFem": "All",
    "reports.filter.selectCountry": "Select country",
    "reports.recruitment.temp": "Temporary (TEMP)",
    "reports.recruitment.temporary": "Temporary (TEMPORARY)",
    "reports.recruitment.permanent": "Permanent",
    "reports.mmr.title": "MMR report",
    "reports.mmr.subtitle": "Monthly fill rate and indicators",
    "reports.mmr.loadError": "Could not load the MMR report. Please try again.",
    "reports.rbm.title": "Requisitions by month",
    "reports.rbm.subtitle": "Monthly volume and indicators",
    "reports.rbm.loadError": "Could not load the Requisitions by month report. Please try again.",
    "reports.perf.title": "Performance",
    "reports.perf.subtitle": "Performance summary by recruiter",
    "reports.perf.loadError": "Could not load the performance report. Please try again.",
    "reports.perf.kpiTitle": "FILL RATE",
    "reports.perf.filter.month": "Month",
    "reports.perf.col.recruiter": "Recruiter",
    "reports.perf.col.opening": "Opening orders",
    "reports.perf.col.temp": "Temporary orders obtained",
    "reports.perf.col.cancellations": "Cancelled orders",
    "reports.perf.col.associateStarts": "Associate starts (Placement)",
    "reports.perf.col.monthEnd": "Orders (month end)",
    "reports.perf.col.fillRate": "Fill rate",
    "reports.perf.col.cancelRate": "Cancellation rate",
    "reports.perf.col.total": "TOTAL",
    "reports.filter.businessUnitShort": "Business unit",
    "reports.filter.requisition": "Requisition",
    "reports.filter.status": "Status",
    "reports.filter.startDate": "Start date",
    "reports.filter.endDate": "End date",
    "reports.filter.client": "Client",
    "reports.filter.clientPlaceholder": "Search client",
    "reports.filter.clientClear": "Clear client",
    "reports.filter.orderNumber": "Order #{id}",
    "reports.sbr.subtitle": "Aggregated by requisition status",
    "reports.sbr.loadError": "Could not load the Status by requisition report. Please try again.",
    "reports.sbr.chartTitle": "Requisitions by status",
    "reports.sbr.empty": "No information",
    "reports.sbr.col.status": "Status",
    "reports.sbr.col.requisitions": "Requisitions",
    "reports.sbr.col.positions": "Number of positions",
    "reports.sbr.col.applicants": "Applicants",
    "reports.sbr.col.preselected": "Preselected",
    "reports.sbr.col.selected": "Selected",
    "reports.sbr.col.evaluated": "Evaluated",
    "reports.sbr.col.interviewed": "Interviewed",
    "reports.sbr.col.prehired": "Pre-hired",
    "reports.sbr.col.hired": "Hired",
    "reports.sbr.col.uncovered": "Uncovered",
    "reports.sbr.col.compliance": "Compliance %",
    "reports.sbr.col.digitalDocs": "Digital docs",
    "reports.sbr.status.covered": "Covered",
    "reports.sbr.status.partiallyCovered": "Partially covered",
    "reports.sbr.status.inAnalysis": "In analysis",
    "reports.sbr.status.inSelection": "In selection",
    "reports.sbr.status.cancelled": "Cancelled",
    "reports.sbr.status.cancellationRequested": "Cancellation requested",
    "reports.sbr.status.inProcess": "In process",
    "reports.month.jan": "Jan",
    "reports.month.feb": "Feb",
    "reports.month.mar": "Mar",
    "reports.month.apr": "Apr",
    "reports.month.may": "May",
    "reports.month.jun": "Jun",
    "reports.month.jul": "Jul",
    "reports.month.aug": "Aug",
    "reports.month.sep": "Sep",
    "reports.month.oct": "Oct",
    "reports.month.nov": "Nov",
    "reports.month.dec": "Dec",
}
